name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby 4
      uses: ruby/setup-ruby@v1
      with:
        # Specifies Ruby 4.0; can also accept explicit semantic versions like '4.0.0'
        ruby-version: '4.0.7' 
        # Enables automatic 'bundle install' with smart hashing-based caching
        bundler-cache: true 

    # Runs a single command using the runners shell
    - name: Add RSPEC dependency
      run: gem install rspec
        
    - name: Run tests
      run: rspec
